---
title: "List of publications"
---

```{r}
#| label: publications
#| warning: false
#| echo: false
#| eval: true

library(tidyverse)
library(vitae)

# All rows
all_entries <- bibliography_entries("biblio_cv.bib") %>%
  mutate(year = format(issued),
         names = author$family,
         first_names = author$given) %>% 
  dplyr::select(all_of(c("names", "first_names", "container-title", "year", "title", "URL"))) %>% 
  arrange(desc(year)) %>% 
  rename(journal = "container-title")
## Function to print one row

get_initial_list <- function(prenoms){
  strsplit(prenoms, ",\\s*") %>% 
    lapply(function(x){
      gsub(pattern = "([A-Z])[[:alpha:]]*", replacement = "\\1.", x = x) %>% 
        gsub(pattern = "\\s+", replacement = "") %>% 
        gsub(pattern = "-", replacement = "")
    })
}

print_entry <- function(names, first_names, journal, year, title, URL){
  noms <- strsplit(names, ",\\s*")
  initiales <- get_initial_list(first_names)
  auteurs <- map2_chr(.x = noms, .y = initiales, function(.x, .y){
    paste(.x, .y, sep = ", ") %>% 
      paste(collapse = ", ")
  })
  if(!is.na(URL)){
    title <- paste0("[", title, "](", URL,")")
  }
  paste0("1. **(", year,"**) ", auteurs, " ", title, " *",journal, "*. \n ")
}


```

```{r}
#| label: print-in-doc
#| results: asis

pmap(all_entries, print_entry) %>% 
  set_names(NULL) %>% 
  do.call(what = cat)
```